FROM node:12-alpine AS builder

ADD . /app
WORKDIR /app
RUN npm install && npm run build

FROM node:12-alpine

RUN npm install -g serve

COPY --from=builder /app/build /app

USER 1100:1100
EXPOSE 8080
ENTRYPOINT [ "serve", "-l", "8080", "/app" ]
